name: "Ansible Playbook"
description: "Run Ansible Playbooks"
inputs:
  path:
    required: true
    description: "Ansible playbook path."
  ssh_private_key:
    required: true
    description: "SSH Private key"
  # vault_password:
  #   required: false
  #   description: "Vault password"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Provisioning User & Databases
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yaml
        directory: $PATH
        key: $SSH_PRIVATE_KEY
        # requirements: requirements.yaml
        # vault_password: $VAULT_PASSWORD
        inventory: |
          [openvpn-engineer]
          34.101.252.165s
      env:
        PATH: ${{ inputs.path }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
        # VAULT_PASSWORD: ${{ inputs.vault_password }}
